builds:
  - id: "casket"
    main: main.go
    dir: ./casket
    binary: casket
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm

dockers:
  - image_templates:
    - "gcr.io/tmpim/casket:latest"
    - "gcr.io/tmpim/casket:{{ .Tag }}"
    - "gcr.io/tmpim/casket:{{ .Tag }}-{{ .Env.GO_VERSION }}"
    - "gcr.io/tmpim/casket:v{{ .Major }}"

before:
  hooks:
    - sh ./.prerelease.sh

archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  algorithm: sha256

release:
  github:
    owner: tmpim
    name: casket
  draft: true
  prerelease: auto
