builds:
  - id: "casket"
    main: main.go
    dir: ./casket
    binary: casket
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
    hooks:
      pre:
       - cmd: go mod init casket
         dir: "{{ dir .Path }}"


archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  algorithm: sha256

release:
  github:
    owner: tmpim
    name: casket
  draft: true
  prerelease: auto